services:
  traefik:
    extends:
      file: "./traefik/docker-compose.yml"
      service: traefik
    environment:
      TRAEFIK_HOST: ${TRAEFIK_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=tlschallenge"
      - "traefik.http.routers.traefik-secure.middlewares=cors,traefik-auth"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}"
    networks:
      - traefik_network

  portainer:
    extends:
      file: "./portainer/compose.portainer.yml"
      service: portainer
    environment:
      PORTAINER_HOST: ${PORTAINER_HOST}
      PORTAINER_LOADBALANCER_PORT: ${PORTAINER_LOADBALANCER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      - "traefik.http.routers.portainer-secure.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=tlschallenge"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_LOADBALANCER_PORT}"
    networks:
      - traefik_network

  storefront:
    extends:
      file: "../frontend/compose.storefront.yaml"
      service: storefront
    environment:
      STOREFRONT_HOST: ${STOREFRONT_HOST}
      STOREFRONT_LOADBALANCER_PORT: ${STOREFRONT_LOADBALANCER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.rule=Host(`${STOREFRONT_HOST}`)"
      - "traefik.http.routers.storefront.entrypoints=web"
      - "traefik.http.routers.storefront-secure.entrypoints=websecure"
      - "traefik.http.routers.storefront-secure.rule=Host(`${STOREFRONT_HOST}`)"
      - "traefik.http.routers.storefront-secure.tls=true"
      - "traefik.http.routers.storefront-secure.tls.certresolver=tlschallenge"
      - "traefik.http.routers.storefront-secure.service=storefront"
      - "traefik.http.services.storefront.loadbalancer.server.port=${STOREFRONT_LOADBALANCER_PORT}"
    networks:
      - traefik_network

  db:
    extends:
      file: "../woocommerce/docker-compose.yaml"
      service: db
    networks:
      - traefik_network

  woocommerce:
    extends:
      file: "../woocommerce/docker-compose.yaml"
      service: wordpress
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp.rule=Host(`${WOOCOMMERCE_HOST}`)"
      - "traefik.http.routers.wp.entrypoints=web"
      - "traefik.http.routers.wp-secure.entrypoints=websecure"
      - "traefik.http.routers.wp-secure.rule=Host(`${WOOCOMMERCE_HOST}`)"
      - "traefik.http.routers.wp-secure.tls=true"
      - "traefik.http.routers.wp-secure.tls.certresolver=tlschallenge"
      - "traefik.http.routers.wp-secure.service=woocommerce"
      - "traefik.http.services.woocommerce.loadbalancer.server.port=${WOOCOMMERCE_LOADBALANCER_PORT}"
    networks:
      - traefik_network

volumes:
  portainer_data:
  redis_data:
  db_data:

networks:
  traefik_network:
    external: true
