include:
  - "./traefik/compose.traefik.yml"
  - "./portainer/compose.portainer.yml"

services:
  storefront:
    extends:
      file: "../frontend/compose.storefront.yaml"
      service: storefront
    environment:
      storefront_HOST: ${storefront_HOST}
      storefront_LOADBALANCER_PORT: ${storefront_LOADBALANCER_PORT}
    labels:
      - 'traefik.enable=true'
      # routers entrypoints
      - 'traefik.http.routers.storefront.entrypoints=web'
      - 'traefik.http.routers.storefront-secure.entrypoints=websecure'
      # routers rules
      - 'traefik.http.routers.storefront.rule=Host(`${storefront_HOST}`)'
      - 'traefik.http.routers.storefront-secure.rule=Host(`${storefront_HOST}`)'
      # middlewares
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      # apply middlewares to routers
      - 'traefik.http.routers.storefront.middlewares=redirect-to-https'
      # tls and certificates
      - 'traefik.http.routers.storefront-secure.tls=true'
      - 'traefik.http.routers.storefront-secure.tls.certresolver=tlschallenge'
      # apply services to routers
      - 'traefik.http.routers.storefront-secure.service=storefront'
      # services
      - 'traefik.http.services.storefront.loadbalancer.server.port=${storefront_LOADBALANCER_PORT}'
    networks:
      - traefik_network
  
  woocommerce:
    extends:
      file: "../woocommerce/docker-compose.yaml"
      service: wordpress
    labels:
      - 'traefik.enable=true'
      # routers entrypoints
      - 'traefik.http.routers.woocommerce.entrypoints=web'
      - 'traefik.http.routers.woocommerce-secure.entrypoints=websecure'
      # routers rules
      - 'traefik.http.routers.woocommerce.rule=Host(`${WOOCOMMERCE_HOST}`)'
      - 'traefik.http.routers.woocommerce-secure.rule=Host(`${WOOCOMMERCE_HOST}`)'
      # middlewares
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      # apply middlewares to routers
      - 'traefik.http.routers.woocommerce.middlewares=redirect-to-https'
      # tls and certificates
      - 'traefik.http.routers.woocommerce-secure.tls=true'
      - 'traefik.http.routers.woocommerce-secure.tls.certresolver=tlschallenge'
      # apply services to routers
      - 'traefik.http.routers.woocommerce-secure.service=woocommerce'
      # services
      - 'traefik.http.services.woocommerce.loadbalancer.server.port=${WOOCOMMERCE_LOADBALANCER_PORT}'
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
