version: "3.3"

services:
  traefik:
    image: "traefik:v3.4"
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./certificates/acme.json:/etc/traefik/acme.json:rw
    environment:
      TRAEFIK_HOST: ${TRAEFIK_HOST}
      TRAEFIK_LOADBALANCER_PORT: ${TRAEFIK_LOADBALANCER_PORT}
    labels:
      - "traefik.enable=true"
      
      # HTTP роутер для редиректа на HTTPS
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTPS роутер для безопасного соединения
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=tlschallenge"
      
      # Защита от несанкционированных доступов на дашборд
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      
      # Дополнительные заголовки для безопасности
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
