# traefik static conf

# comment this in production
api:
  dashboard: true   # set to false in production 
  insecure: true    # set to false in production 
  debug: true       # set to false in production 

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: traefik_network
  file:
    filename: /etc/traefik./dynamic.yaml
    watch: true

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  tlschallenge:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # IMPORTANT: comment out this line to get production ready certificates. After this, clear acme.json file.
      email: foobar@example.invalid
      storage: /etc/traefik/acme.json # chmod 600 this file on the host system / измените доступ к файлу chmod 600
      tlsChallenge: {}

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
accessLog:
  filePath: "/var/log/traefik/access.log"

global:
  checkNewVersion: true

