docRoot                   /var/www/vhosts/yuliatabbouleh.ru/html
vhDomain                  yuliatabbouleh.ru
enableGzip                1
disableGzipFileTypes      css,js,gif,jpg,jpeg,png,swf,woff,woff2,eot,ttf,svg,ico
enableCompression         1

# Логирование
errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                WARN
  rollingSize             50M
  keepDays                30
}
accessLog $VH_ROOT/logs/access.log {
  useServer               0
  rollingSize             50M
  keepDays                30
  logReferer              1
  logUserAgent            1
}

# Настройка PHP через LSAPI (замените lsphp73 на используемую версию PHP)
extprocessor lsphp74 {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp74.sock
  maxConns                50
  env                     PHP_LSAPI_MAX_REQUESTS=500
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               1
  path                    $SERVER_ROOT/lsphp74/bin/lsphp
  backlog                 100
  instances               2
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           400
  procHardLimit           500
  cpuSoftLimit            25
  cpuHardLimit            35
}

scriptHandler {
  add                     lsapi:lsphp74
}

# Основной контекст (каталог сайта)
context / {
  type                    static
  location                $VH_ROOT/html
  allowBrowse             1
  indexFiles              index.php,index.html
  expires                 5d
}

context /favicon.ico {
  type                    static
  location                $VH_ROOT/html
  allowBrowse             0
  expires                 30d
}

context /robots.txt {
  type                    static
  location                $VH_ROOT/html
  allowBrowse             0
  expires                 1d
}

# ЧПУ для WordPress / перезаписывающие правила
rewrite  {
  enable                  1
  autoLoadHtaccess        1
  rewriteFile             $VH_ROOT/html/.htaccess
}

# Защита WooCommerce cookies на уровне сервера, если применимо
header {
  add                     Set-Cookie "SameSite=Lax; Secure"
}

# Настроим увеличение времени ожидания (таймауты), важные для WooCommerce транзакций
timeout {
  readTimeout             300
  writeTimeout            300
  idleTimeout             300
}

# Безопасность дополнительных файлов (от запроса к core файлов WordPress)
context /wp-config.php {
  type                    null
}
context /wp-admin/install.php {
  type                    null
}

logLevel                INFO
